name: available_on_offline
description: Example app
author: Mochamad Nizwar Syafuan <nizwar@merahputih.id>
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
  simplehttpconnection: ^1.3.1
  path_provider: ^1.6.0
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
